apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 058264486189.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 058264486189.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 3ded7efd
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
